version: "3.8"
services:
  web:
    ports:
      # We only bind ports directly in development:
      - "8000:8000"
    volumes:
      # We only mount source code in development:
      - .:/code
    environment:
      FLASK_ENV: development
